"""Architecture story generator — produces a full decision document from structured engine output."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime

from storage_advisor.architecture.builder import ArchitectureOutput
from storage_advisor.domain.recommendations import RecommendationResult
from storage_advisor.domain.scenario import Scenario
from storage_advisor.estimation.impact_estimator import ImpactReport


@dataclass
class ArchitectureStory:
    title: str
    generated_at: str
    sections: dict[str, str]
    full_document: str
    word_count: int
    source: str


class ArchitectureStoryGenerator:

    def generate(
        self,
        scenario: Scenario,
        result: RecommendationResult,
        impact: ImpactReport,
        architecture: ArchitectureOutput,
        trajectory=None,
        banded_impact=None,
    ) -> ArchitectureStory:
        title_line = (
            f"Storage Architecture Decision — "
            f"{scenario.business_domain.replace('_', ' ').title()}"
        )

        context = self._build_context(scenario, result, architecture)
        decisions_text = self._build_decisions(result, architecture)
        rejected_text = self._build_rejected(scenario, result)
        risks_text = self._build_risks(scenario, result, architecture, trajectory)
        sequence_text = self._build_sequence(scenario, result, architecture)
        questions_text = self._build_questions(scenario)

        impact_note = ""
        if banded_impact:
            impact_note = (
                f"\n\n*Confidence ranges (25th–75th percentile from "
                f"{banded_impact.storage_band.sample_size} similar scenarios): "
                f"storage {banded_impact.storage_band.low:.0f}–"
                f"{banded_impact.storage_band.high:.0f}%, "
                f"cost {banded_impact.cost_band.low:.0f}–"
                f"{banded_impact.cost_band.high:.0f}%.*"
            )

        now_str = datetime.now().strftime("%Y-%m-%d %H:%M")

        full_document = (
            f"# {title_line}\n"
            f"*Generated: {now_str} | "
            f"Engine: AI Data Architect v1.0 | "
            f"Source: deterministic rule engine*\n\n"
            f"---\n\n"
            f"## Context\n\n{context}\n\n"
            f"---\n\n"
            f"## Key Architectural Decisions\n\n{decisions_text}\n\n"
            f"---\n\n"
            f"## What We Explicitly Rejected\n\n{rejected_text}\n\n"
            f"---\n\n"
            f"## Model-Based Impact Estimates\n\n"
            f"*These are synthetic estimates derived from documented assumptions — "
            f"not empirical production measurements.*\n\n"
            f"- Storage: {scenario.current_storage_gb:,.0f} GB → "
            f"{impact.storage.projected_storage_gb:,.0f} GB "
            f"({impact.storage.estimated_reduction_pct:.1f}% reduction)\n"
            f"- Monthly cost: ${impact.cost.estimated_monthly_baseline_usd:,.0f} → "
            f"${impact.cost.estimated_monthly_optimized_usd:,.0f} "
            f"({impact.cost.estimated_savings_pct:.1f}% reduction)\n"
            f"- Latency: {impact.latency.current_effective_latency_ms:.0f}ms → "
            f"{impact.latency.estimated_optimized_latency_ms:.0f}ms "
            f"({impact.latency.estimated_improvement_pct:.1f}% improvement)"
            f"{impact_note}\n\n"
            f"---\n\n"
            f"## Top 3 Risks\n\n{risks_text}\n\n"
            f"---\n\n"
            f"## 90-Day Implementation Sequence\n\n{sequence_text}\n\n"
            f"---\n\n"
            f"## Open Questions\n\n{questions_text}\n\n"
            f"---\n\n"
            f"*Document generated by AI Data Architect rule engine. "
            f"All estimates are model-based. Review with your engineering team "
            f"before implementation.*"
        )

        sections = {
            "Context": context,
            "Key Architectural Decisions": decisions_text,
            "What We Explicitly Rejected": rejected_text,
            "Top 3 Risks": risks_text,
            "90-Day Implementation Sequence": sequence_text,
            "Open Questions": questions_text,
        }

        return ArchitectureStory(
            title=title_line,
            generated_at=datetime.now().isoformat(),
            sections=sections,
            full_document=full_document,
            word_count=len(full_document.split()),
            source="structured_engine",
        )

    def _build_context(
        self,
        scenario: Scenario,
        result: RecommendationResult,
        architecture: ArchitectureOutput,
    ) -> str:
        critical = [
            p for p in result.detected_problems
            if p.get("severity") == "CRITICAL"
        ]
        high = [
            p for p in result.detected_problems
            if p.get("severity") == "HIGH"
        ]

        if critical:
            dominant = critical[0].get("problem_id", "").replace("_", " ").lower()
        elif high:
            dominant = high[0].get("problem_id", "").replace("_", " ").lower()
        elif result.detected_problems:
            dominant = result.detected_problems[0].get("problem_id", "").replace("_", " ").lower()
        else:
            dominant = "scale requirements"

        compliance = [
            c for c in scenario.compliance_requirements if c != "NONE"
        ]
        compliance_str = (
            f" | Compliance: {', '.join(compliance)}" if compliance else ""
        )

        data_types_str = ", ".join(str(d) for d in scenario.data_types)

        return (
            f"**Workload:** {scenario.business_domain.replace('_', ' ').title()} | "
            f"{scenario.expected_users:,} users | "
            f"{scenario.daily_growth_gb} GB/day growth | "
            f"{data_types_str} data\n\n"
            f"**Requirements:** {scenario.latency_requirement_ms}ms latency target, "
            f"{scenario.availability_requirement}% availability SLA, "
            f"{scenario.retention_years}-year retention"
            f"{compliance_str}\n\n"
            f"**Analysis summary:** The workload profiler identified "
            f"{len(result.detected_problems)} architectural pressures — "
            f"{len(critical)} critical and {len(high)} high severity. "
            f"{dominant.capitalize()} is the dominant concern. "
            f"The recommended architecture comprises {len(architecture.components)} "
            f"components addressing {len(result.recommendations)} optimization areas."
        )

    def _build_decisions(
        self,
        result: RecommendationResult,
        architecture: ArchitectureOutput,
    ) -> str:
        required = [r for r in result.recommendations if r.priority == "REQUIRED"]
        top_recommended = [
            r for r in result.recommendations if r.priority == "RECOMMENDED"
        ][:2]

        decisions = []
        for rec in required + top_recommended:
            component = next(
                (c for c in architecture.components if rec.technique_id in c.required_by),
                None,
            )
            service_str = f" (implemented via {component.service})" if component else ""
            trade_off = rec.disadvantages[0] if rec.disadvantages else "Adds operational complexity."

            decisions.append(
                f"**{rec.technique_id.replace('_', ' ').title()}** [{rec.priority}]"
                f"{service_str}: {rec.rationale} "
                f"Trade-off: {trade_off}"
            )

        return "\n\n".join(decisions) if decisions else "No decisions to report."

    def _build_rejected(
        self,
        scenario: Scenario,
        result: RecommendationResult,
    ) -> str:
        optional = [r for r in result.recommendations if r.priority == "OPTIONAL"][:3]
        alt = (
            result.alternatives[1] if len(result.alternatives) > 1
            else result.alternatives[0] if result.alternatives
            else None
        )

        rejected_items = []

        if alt:
            rejected_items.append(
                f"**{alt.label}:** {alt.focus}. "
                f"Rejected because: {alt.trade_off}"
            )

        for opt in optional:
            trade_off = opt.disadvantages[0] if opt.disadvantages else "Not beneficial for this workload."
            rejected_items.append(
                f"**{opt.technique_id.replace('_', ' ').title()}** (scored as OPTIONAL): "
                f"{trade_off} — "
                f"not recommended for this workload profile."
            )

        if not rejected_items:
            rejected_items.append(
                f"All 19 techniques were evaluated. The conflict resolver eliminated "
                f"techniques that conflict with the required high-availability configuration. "
                f"A lean architecture (REQUIRED techniques only) was considered but rejected "
                f"given the {scenario.retention_years}-year retention requirement."
            )

        return "\n\n".join(rejected_items)

    def _build_risks(
        self,
        scenario: Scenario,
        result: RecommendationResult,
        architecture: ArchitectureOutput,
        trajectory,
    ) -> str:
        risks = []

        if result.detected_problems:
            top_problem = result.detected_problems[0]
            pid = top_problem.get("problem_id", "Unknown").replace("_", " ").title()
            sev = top_problem.get("severity", "HIGH")
            risks.append(
                f"**{pid} [{sev}]:** "
                f"Mitigated by the recommended architecture, but requires "
                f"operational discipline to maintain."
            )

        first_service = (
            architecture.components[0].service
            if architecture.components else "distributed systems"
        )
        risks.append(
            f"**Operational complexity:** The recommended "
            f"{len(result.recommendations)}-technique strategy introduces "
            f"{len(architecture.components)} distinct infrastructure components. "
            f"Each adds an operational surface area. "
            f"Teams without prior experience with {first_service} "
            f"should budget 2–4 weeks for ramp-up."
        )

        if trajectory and trajectory.snapshots:
            risks.append(
                f"**Cost trajectory:** Model-based estimates project monthly AWS costs "
                f"growing from ${trajectory.snapshots[0].real_cost_usd:,.0f} to "
                f"${trajectory.snapshots[-1].real_cost_usd:,.0f} over "
                f"{trajectory.months_simulated} months at 5% monthly user growth. "
                f"The architecture requires structural changes at month "
                f"{trajectory.architecture_stable_until} "
                f"({len(trajectory.tipping_points)} tipping points identified). "
                f"Plan for these transitions proactively."
            )
        else:
            risks.append(
                f"**Cost growth:** At {scenario.daily_growth_gb} GB/day current growth, "
                f"storage costs will compound significantly over "
                f"{scenario.retention_years} years. "
                f"The lifecycle management and tiered storage recommendations "
                f"are essential to managing this — skipping them shifts cost risk forward."
            )

        return "\n\n".join(risks)

    def _build_sequence(
        self,
        scenario: Scenario,
        result: RecommendationResult,
        architecture: ArchitectureOutput,
    ) -> str:
        required_techs = [r for r in result.recommendations if r.priority == "REQUIRED"]
        recommended_techs = [r for r in result.recommendations if r.priority == "RECOMMENDED"]

        def _service_for(rec):
            return next(
                (c.service for c in architecture.components if rec.technique_id in c.required_by),
                "infrastructure",
            )

        req_lines = "\n".join(
            f"  - {r.technique_id.replace('_', ' ').title()} via {_service_for(r)}"
            for r in required_techs[:3]
        )

        rec_lines = "\n".join(
            f"  - {r.technique_id.replace('_', ' ').title()}: "
            f"{r.rationale[:80]}{'...' if len(r.rationale) > 80 else ''}"
            for r in recommended_techs[:3]
        )

        concurrent_test = int(scenario.expected_users * 0.1)
        pct = int(concurrent_test / scenario.expected_users * 100)

        return (
            f"**Days 1–30 — Foundation (REQUIRED components)**\n\n"
            f"Deploy the non-negotiable infrastructure first.\n"
            f"{req_lines}\n\n"
            f"Validate SLOs before proceeding: latency target "
            f"{scenario.latency_requirement_ms}ms, "
            f"availability {scenario.availability_requirement}%.\n\n"
            f"**Days 31–60 — Optimization (RECOMMENDED components)**\n\n"
            f"Layer in the optimization techniques once the foundation is stable.\n"
            f"{rec_lines}\n\n"
            f"**Days 61–90 — Observability and cost controls**\n\n"
            f"- Instrument all components for latency, throughput, and error rate\n"
            f"- Set S3 lifecycle rules for {scenario.retention_years}-year retention policy\n"
            f"- Configure cost alerts at 110% of model-based baseline\n"
            f"- Load test to {concurrent_test:,} concurrent users "
            f"({pct}% of total user base)"
        )

    def _build_questions(self, scenario: Scenario) -> str:
        questions = []

        compliance = [c for c in scenario.compliance_requirements if c != "NONE"]
        if not compliance:
            questions.append(
                "**Compliance scope:** No compliance requirements were specified. "
                "If GDPR, HIPAA, or PCI apply in future markets, "
                "the architecture will require encryption key management "
                "and audit logging additions."
            )

        questions.append(
            f"**Peak load profile:** The scenario specifies {scenario.expected_users:,} "
            f"total users but not peak concurrent load. "
            f"If concurrent users exceed 10% of total during peak events, "
            f"the ElastiCache tier may need vertical scaling before month 6."
        )

        questions.append(
            "**Read/write ratio by data type:** Images and transactional data "
            "have different access patterns. Confirming the read ratio for each "
            "type separately would allow more precise caching and partitioning "
            "strategy."
        )

        if scenario.retention_years >= 7:
            questions.append(
                f"**Retrieval SLA for archived data:** The {scenario.retention_years}-year "
                f"retention policy is implemented with Glacier lifecycle rules. "
                f"Confirm whether archived data needs same-day retrieval "
                f"(Glacier Instant) or can tolerate 12-hour retrieval "
                f"(Glacier Deep Archive, ~70% cheaper)."
            )

        return "\n\n".join(questions[:4])
